{
  throw new FunctorException("ExceptionTransformer invoked");
}
