{
  try {
    resource.close();
  }
 catch (  Exception e) {
  }
}
