{
  try {
    esTester.client().prepareGet().execute();
    fail();
  }
 catch (  Exception e) {
    assertThat(e).isInstanceOf(UnsupportedOperationException.class).hasMessage("execute() should not be called as it's used for asynchronous");
  }
}
