{
  Exception cause=new Exception("cause");
  ContextException e=ContextException.of(cause);
  assertThat(e.getMessage()).isEqualTo("java.lang.Exception: cause");
  assertThat(e.getRawMessage()).isEqualTo("java.lang.Exception: cause");
  assertThat(e.getCause()).isSameAs(cause);
}
